<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yukun Wang">

<title>JSC370 Midterm: Daily PM2.5 and Weather Conditions Across Major U.S. Metropolitan Areas in 2024</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js" integrity="sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2" crossorigin="anonymous"></script><script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/clipboard/clipboard.min.js"></script>
<script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/popper.min.js"></script>
<script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/anchor.min.js"></script>
<link href="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="JSC370_midterm_PM25_NOAA_AQS2.0_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js" integrity="sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#project-introduction-10-points" id="toc-project-introduction-10-points" class="nav-link active" data-scroll-target="#project-introduction-10-points">Project Introduction (10 points)</a></li>
  <li><a href="#methods-20-points" id="toc-methods-20-points" class="nav-link" data-scroll-target="#methods-20-points">Methods (20 points)</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources">Data sources</a></li>
  <li><a href="#variable-construction" id="toc-variable-construction" class="nav-link" data-scroll-target="#variable-construction">Variable construction</a></li>
  <li><a href="#cleaning-and-preprocessing" id="toc-cleaning-and-preprocessing" class="nav-link" data-scroll-target="#cleaning-and-preprocessing">Cleaning and preprocessing</a></li>
  <li><a href="#planned-analyses" id="toc-planned-analyses" class="nav-link" data-scroll-target="#planned-analyses">Planned analyses</a></li>
  <li><a href="#data-generation-and-api-retrieval" id="toc-data-generation-and-api-retrieval" class="nav-link" data-scroll-target="#data-generation-and-api-retrieval">Data generation and api retrieval</a></li>
  <li><a href="#data-cleaning-and-wrangling" id="toc-data-cleaning-and-wrangling" class="nav-link" data-scroll-target="#data-cleaning-and-wrangling">Data cleaning and wrangling</a></li>
  </ul></li>
  <li><a href="#preliminary-results-30-points" id="toc-preliminary-results-30-points" class="nav-link" data-scroll-target="#preliminary-results-30-points">Preliminary Results (30 points)</a>
  <ul class="collapse">
  <li><a href="#basic-dataset-summary" id="toc-basic-dataset-summary" class="nav-link" data-scroll-target="#basic-dataset-summary">Basic dataset summary</a></li>
  <li><a href="#temporal-patterns-monthly-and-seasonal-pm2.5" id="toc-temporal-patterns-monthly-and-seasonal-pm2.5" class="nav-link" data-scroll-target="#temporal-patterns-monthly-and-seasonal-pm2.5">Temporal Patterns: Monthly and Seasonal PM2.5</a></li>
  <li><a href="#spatial-patterns-top-metropolitan-areas" id="toc-spatial-patterns-top-metropolitan-areas" class="nav-link" data-scroll-target="#spatial-patterns-top-metropolitan-areas">Spatial Patterns: Top Metropolitan Areas</a></li>
  <li><a href="#weather-and-pm2.5-relationships" id="toc-weather-and-pm2.5-relationships" class="nav-link" data-scroll-target="#weather-and-pm2.5-relationships">Weather and PM2.5 Relationships</a></li>
  </ul></li>
  <li><a href="#summary-15-points" id="toc-summary-15-points" class="nav-link" data-scroll-target="#summary-15-points">Summary (15 points)</a>
  <ul class="collapse">
  <li><a href="#answer-to-the-proposed-research-questions" id="toc-answer-to-the-proposed-research-questions" class="nav-link" data-scroll-target="#answer-to-the-proposed-research-questions">Answer to the proposed research questions</a></li>
  <li><a href="#final-project-objectives" id="toc-final-project-objectives" class="nav-link" data-scroll-target="#final-project-objectives">Final Project Objectives</a></li>
  <li><a href="#implementation-plan" id="toc-implementation-plan" class="nav-link" data-scroll-target="#implementation-plan">Implementation Plan</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">JSC370 Midterm: Daily PM2.5 and Weather Conditions Across Major U.S. Metropolitan Areas in 2024</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yukun Wang </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="project-introduction-10-points" class="level2">
<h2 class="anchored" data-anchor-id="project-introduction-10-points">Project Introduction (10 points)</h2>
<p>PM2.5, or fine particulate matter with aerodynamic diameter less than or equal to 2.5 micrometers, is an important air pollutant because elevated concentrations are associated with worse respiratory and cardiovascular health outcomes. Understanding how PM2.5 changes across time and place is therefore an important public-health and environmental question.</p>
<p>This project studies <strong>daily PM2.5 patterns across major U.S. metropolitan areas in 2024</strong> by combining daily monitor-level PM2.5 data from the EPA AQS platform with daily weather-related variables from NOAA national center. To satisfy the project requirement of using an API, I use the <strong>NOAA Climate Data Online (CDO) Web Services API v2</strong> to retrieve daily <strong>temperature</strong> and <strong>precipitation</strong> data. I then combine those API-based weather measures with daily <strong>wind</strong>, <strong>barometric pressure</strong>, and <strong>relative humidity/dew point</strong> summary files downloaded from the AQS platform.</p>
<p>The main research question is:</p>
<p><strong>How are daily PM2.5 levels associated with temperature, precipitation, wind, barometric pressure, and humidity-related conditions across major U.S. metropolitan areas in 2024?</strong></p>
<p>More specifically, I ask:</p>
<ol type="1">
<li>Which metropolitan areas show higher average daily PM2.5 levels in 2024?</li>
<li>How does PM2.5 vary across months and seasons?</li>
<li>Are higher-PM2.5 days associated with different weather conditions?</li>
</ol>
<p>The final analysis dataset is built at the <strong>CBSA-day</strong> level. I first aggregate monitor-level observations to the metropolitan-area-by-day level and then merge all weather variables onto the same daily metropolitan panel.</p>
</section>
<section id="methods-20-points" class="level2">
<h2 class="anchored" data-anchor-id="methods-20-points">Methods (20 points)</h2>
<section id="data-sources" class="level3">
<h3 class="anchored" data-anchor-id="data-sources">Data sources</h3>
<p>This project combines five daily datasets:</p>
<ol type="1">
<li><strong>EPA AQS daily PM2.5</strong> (<code>daily_88101_2024.csv</code>) as the main outcome dataset.</li>
<li><strong>NOAA CDO API</strong> for daily temperature and precipitation.</li>
<li><strong>EPA AQS daily wind</strong> (<code>daily_WIND_2024.csv</code>).</li>
<li><strong>EPA AQS daily barometric pressure</strong> (<code>daily_PRESS_2024.csv</code>).</li>
<li><strong>EPA AQS daily relative humidity / dew point</strong> (<code>daily_RH_DP_2024.csv</code>).</li>
</ol>
<p>The AQS daily PM2.5 file contains one row per monitor-day observation, including the daily arithmetic mean, daily maximum value, date, and geographic identifiers such as city and CBSA. The weather-related AQS files have a similar structure. Because these files are also reported at the monitor-day level, I aggregate each source to the <strong>CBSA-day</strong> level before merging.</p>
<p>The NOAA API portion is included to meet the requirement that the project use an API. I use the CDO Web Services v2 endpoint with a token in the request header and retrieve daily weather observations from selected stations corresponding to major metropolitan areas.</p>
</section>
<section id="variable-construction" class="level3">
<h3 class="anchored" data-anchor-id="variable-construction">Variable construction</h3>
<p>For PM2.5, the key outcome variable is the daily <strong>arithmetic mean</strong> concentration. I also create a binary <strong>high PM2.5 day</strong> indicator for exploratory analysis using a threshold of 35 µg/m³ at the CBSA-day level:</p>
<ul>
<li><code>high_pm25_day = 1</code> if daily CBSA mean PM2.5 ≥ 35</li>
<li><code>high_pm25_day = 0</code> otherwise</li>
</ul>
<p>For weather, I use:</p>
<ul>
<li><code>TMAX</code>: daily maximum temperature from NOAA</li>
<li><code>TMIN</code>: daily minimum temperature from NOAA</li>
<li><code>PRCP</code>: daily precipitation from NOAA</li>
<li><code>wind_mean</code>: daily mean wind speed from AQS daily wind</li>
<li><code>press_mean</code>: daily mean barometric pressure from AQS daily pressure</li>
<li><code>rh_mean</code>: daily mean relative humidity from AQS daily RH / dewpoint</li>
</ul>
</section>
<section id="cleaning-and-preprocessing" class="level3">
<h3 class="anchored" data-anchor-id="cleaning-and-preprocessing">Cleaning and preprocessing</h3>
<p>The preprocessing workflow is:</p>
<ol type="1">
<li>Read all daily files.</li>
<li>Standardize column names to lower snake_case.</li>
<li>Parse dates.</li>
<li>Remove observations with missing CBSA or missing key outcome values.</li>
<li>Aggregate each source to the <strong>CBSA-day</strong> level.</li>
<li>Merge all sources by <code>cbsa_name</code> and <code>date_local</code>.</li>
<li>Create month, season, and high-pollution indicators.</li>
</ol>
</section>
<section id="planned-analyses" class="level3">
<h3 class="anchored" data-anchor-id="planned-analyses">Planned analyses</h3>
<p>I use exploratory data analysis and summary statistics to describe temporal and spatial patterns in PM2.5. Specifically, I examine:</p>
<ul>
<li>monthly and seasonal PM2.5 patterns</li>
<li>mean PM2.5 by CBSA</li>
<li>top metropolitan areas by annual average PM2.5</li>
<li>relationships between PM2.5 and weather variables using scatterplots and grouped summaries</li>
</ul>
<p>For the final project, this merged dataset could also support a predictive model for daily PM2.5 or high-PM2.5 days.</p>
<p>To begin the analysis, the primary environmental datasets are loaded into the environment. These comprise four separate daily summary files downloaded directly from the EPA Air Quality System (AQS) platform for the year 2024: the main outcome variable (PM2.5) and three supplementary meteorological variables (wind, barometric pressure, and relative humidity/dew point). These raw .csv files serve as the foundational monitor-level observations for the study.</p>
</section>
<section id="data-generation-and-api-retrieval" class="level3">
<h3 class="anchored" data-anchor-id="data-generation-and-api-retrieval">Data generation and api retrieval</h3>
<p>To satisfy the project’s requirement of utilizing an Application Programming Interface (API) and to obtain essential meteorological covariates, I integrate daily weather data from the NOAA Climate Data Online (CDO) Web Services API v2.</p>
<p>Then I design a suite of custom helper functions is defined to interact robustly with the API endpoints. The noaa_get function manages authentication via a unique request token and handles potential connection errors.</p>
<p>Because of the NOAA API limits the number of records returned per request, the fetch_noaa_data function is designed with a pagination loop (using the offset parameter) to iteratively pull all available rows for a given station and date range. Additional functions are included to verify station validity and extract available datatypes.</p>
<p>The NOAA CDO API queries data at the individual weather station level rather than by city. To align this weather data with the AQS pollution data, I construct a mapping dictionary (metro_station_map). This dictionary links major U.S. Core Based Statistical Areas (CBSAs)—such as New York, Los Angeles, and Chicago—to the specific Global Historical Climatology Network Daily (GHCND) station ID that best represents the metropolitan area’s general weather conditions.</p>
<p>With the API helper functions and the CBSA-to-station mapping established, the data retrieval process is executed. The code iterates through the predefined dictionary of major metropolitan areas, calling the fetch_noaa_weather_bundle function for each station. Specifically, it requests daily maximum temperature (TMAX), minimum temperature (TMIN), and precipitation (PRCP) for the entire year of 2024. The successfully retrieved records are appended into a single, long-format DataFrame (noaa_weather_raw), which is later reshaped and merged with the EPA AQS datasets.</p>
</section>
<section id="data-cleaning-and-wrangling" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning-and-wrangling">Data cleaning and wrangling</h3>
<section id="standardize-column-names" class="level4">
<h4 class="anchored" data-anchor-id="standardize-column-names">Standardize column names</h4>
<p>To ensure consistency across the multiple EPA AQS datasets, the first step in the data wrangling process is to standardize all column names. The clean_columns function converts all headers to lowercase, strips trailing whitespaces, and replaces spaces and special characters with underscores (snake_case format). This step minimizes referencing errors during the merging phase.</p>
</section>
<section id="parse-dates" class="level4">
<h4 class="anchored" data-anchor-id="parse-dates">Parse dates</h4>
<p>Next, the date columns across all four datasets (PM2.5, Wind, Barometric Pressure, and Relative Humidity) are converted from string format to pandas datetime objects. The dt.normalize() function is applied to strip any inconsistent timestamp information, ensuring that all dates are standardized at midnight for accurate daily merging.</p>
</section>
<section id="build-location-day-datasets" class="level4">
<h4 class="anchored" data-anchor-id="build-location-day-datasets">Build location-day datasets</h4>
<p>A key challenge with the AQS datasets is the presence of multiple Parameter Occurrence Codes (POC) at a single monitoring site on the same day. These represent multiple instruments operating simultaneously. To handle this and create a clean unit of observation, I construct a unique location-day identifier (location_day_keys) using state_code, county_code, site_num, and date_local.</p>
<p>The aggregate_to_location_day function is then applied to group the data by these unique keys. If a site has multiple monitors, the function calculates the mean of the daily arithmetic means, collapses the geographic identifiers, and returns a dataset strictly at the site-day level.</p>
</section>
<section id="merge-aqs-supplemental-data-and-noaa-weather" class="level4">
<h4 class="anchored" data-anchor-id="merge-aqs-supplemental-data-and-noaa-weather">Merge AQS supplemental data and NOAA weather</h4>
<p>With all datasets aggregated to the site-day level, I conduct a sequence of merges to build the final comprehensive dataset. First, the AQS meteorological variables (wind, pressure, humidity) are joined to the main PM2.5 dataset using the location_day_keys via a one-to-one left merge.</p>
<p>Subsequently, the NOAA API weather dataset, which is constructed at the broader Core Based Statistical Area (CBSA) level, is integrated. To achieve this, I reshape the NOAA data into a wide format (weather_wide) with one row per CBSA-day. This dataset is then merged into the site-level AQS panel using a many-to-one left join based on cbsa_name and date_local. Finally, new categorical variables such as month, season, and a binary indicator for high_pm25_day (≥ 35 µg/m³) are generated to facilitate exploratory data analysis.</p>
<p>The final preprocessing step involves handling missing values to prepare the dataset for complete-case analysis. Because the NOAA API data was pulled exclusively for specific major metropolitan areas, AQS monitors located outside these CBSAs lack temperature and precipitation data. Furthermore, some monitors may have missed recording certain meteorological parameters on given days. Therefore, I subset the data by removing any rows containing missing values across the core variables, yielding the final analytical dataset (merged_local_day).</p>
</section>
</section>
</section>
<section id="preliminary-results-30-points" class="level2">
<h2 class="anchored" data-anchor-id="preliminary-results-30-points">Preliminary Results (30 points)</h2>
<section id="basic-dataset-summary" class="level3">
<h3 class="anchored" data-anchor-id="basic-dataset-summary">Basic dataset summary</h3>
<p>After we merged the dataset from the two different sourse, we notice there is a POC value indicate for the different measure methods and rules for PM2.5, under this condition, we will do the filter again and only remains the data with the POC value as 1. Then we can do a small summary for the data:</p>
<div class="cell" data-message="false" data-execution_count="13">
<div id="tbl-summary" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-message="false" data-execution_count="13">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Table 1: Summary Statistics of PM2.5 and Weather Variables (Primary Monitors Only)
</figcaption>
<div aria-describedby="tbl-summary-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display" data-execution_count="7">
<div>


<table class="dataframe do-not-create-environment cell caption-top table table-sm table-striped small" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">count</th>
<th data-quarto-table-cell-role="th">mean</th>
<th data-quarto-table-cell-role="th">std</th>
<th data-quarto-table-cell-role="th">min</th>
<th data-quarto-table-cell-role="th">50%</th>
<th data-quarto-table-cell-role="th">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<th data-quarto-table-cell-role="th">PM2.5 Mean (µg/m³)</th>
<td>5798.0</td>
<td>9.76</td>
<td>6.68</td>
<td>0.00</td>
<td>8.53</td>
<td>130.94</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Max Temp (°C)</th>
<td>5798.0</td>
<td>20.78</td>
<td>9.04</td>
<td>-16.00</td>
<td>21.10</td>
<td>47.80</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Precipitation (mm)</th>
<td>5798.0</td>
<td>1.96</td>
<td>7.12</td>
<td>0.00</td>
<td>0.00</td>
<td>109.70</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Wind Speed Mean</th>
<td>5798.0</td>
<td>99.09</td>
<td>31.00</td>
<td>3.91</td>
<td>101.29</td>
<td>321.08</td>
</tr>
<tr class="odd">
<th data-quarto-table-cell-role="th">Barometric Pressure (mb)</th>
<td>5798.0</td>
<td>991.62</td>
<td>29.61</td>
<td>823.04</td>
<td>994.67</td>
<td>1044.21</td>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Relative Humidity (%)</th>
<td>5798.0</td>
<td>64.35</td>
<td>18.51</td>
<td>5.71</td>
<td>67.62</td>
<td>100.00</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
</figure>
</div>
</div>
<p>The summary statistics for the 5,798 site-day observations provide a foundational understanding of the 2024 dataset: - PM2.5 Concentrations: The average daily PM2.5 concentration (arithmetic_mean) is 9.76 µg/m³. However, the mean is higher than the median (8.53 µg/m³), indicating a right-skewed distribution caused by extreme pollution events, with a recorded maximum of 130.94 µg/m³. - Temperature Ranges: Maximum temperatures (TMAX) average 20.78°C, but the dataset captures significant extremes ranging from -16°C to 47.8°C. This wide variation ensures that the study accounts for diverse seasonal impacts on air quality. - Precipitation and Humidity: Precipitation is highly skewed, with a median of 0.0 mm, indicating that most days in the sample are dry. The average relative humidity of 64.35% suggests moderate atmospheric moisture levels across the metropolitan areas studied. - Atmospheric Pressure: Barometric pressure remains stable with a mean of 991.62 mb. The minimum of 823.04 mb correctly reflects data from high-altitude monitoring sites, adding to the geographic diversity of the report.</p>
</section>
<section id="temporal-patterns-monthly-and-seasonal-pm2.5" class="level3">
<h3 class="anchored" data-anchor-id="temporal-patterns-monthly-and-seasonal-pm2.5">Temporal Patterns: Monthly and Seasonal PM2.5</h3>
<div id="cell-fig-monthly" class="cell" data-message="false" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-monthly" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-monthly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-monthly-output-1.png" width="951" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monthly-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Figure 1: Monthly Distribution of Daily PM2.5 Concentrations in 2024
</figcaption>
</figure>
</div>
</div>
</div>
<p>The figure reveals a distinct bimodal seasonal pattern in PM2.5 concentrations across 2024. The highest median levels and greatest atmospheric variability occur during the Summer months (July and August) and Winter (January). Notably, July displays the most significant outliers, with daily concentrations spiking above 120 µg/m³. These spikes are often characteristic of exceptional regional events, such as wildfire smoke transport, which significantly skew the distribution upward. In contrast, Spring (April and May) serves as the cleanest period of the year, exhibiting both the lowest median concentrations (~7.75 µg/m³) and the most stable, narrowest interquartile ranges. This seasonal cycle highlights the impact of varying temperature-driven chemical reactions and stagnant winter air masses on urban air quality.</p>
<div class="cell" data-message="false" data-execution_count="15">
<div id="tbl-seasonal" class="cell quarto-float quarto-figure quarto-figure-center anchored" data-message="false" data-execution_count="15">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-seasonal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Table 2: Seasonal Summary of PM2.5 Concentrations
</figcaption>
<div aria-describedby="tbl-seasonal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output cell-output-display cell-output-markdown" data-execution_count="9">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">season</th>
<th style="text-align: right;">count</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">std</th>
<th style="text-align: right;">max</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Fall</td>
<td style="text-align: right;">1415</td>
<td style="text-align: right;">10.14</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">57.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spring</td>
<td style="text-align: right;">1520</td>
<td style="text-align: right;">7.75</td>
<td style="text-align: right;">4.72</td>
<td style="text-align: right;">41.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Summer</td>
<td style="text-align: right;">1484</td>
<td style="text-align: right;">10.67</td>
<td style="text-align: right;">6.5</td>
<td style="text-align: right;">130.94</td>
</tr>
<tr class="even">
<td style="text-align: left;">Winter</td>
<td style="text-align: right;">1379</td>
<td style="text-align: right;">10.62</td>
<td style="text-align: right;">8.63</td>
<td style="text-align: right;">61.7</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The seasonal summary table quantifies the temporal fluctuations of PM2.5 concentrations throughout 2024: - Peak Pollution Periods: Summer and Winter emerge as the seasons with the highest average concentrations, recording means of 10.67 µg/m³ and 10.62 µg/m³, respectively. - Extreme Events: Summer recorded the most severe pollution event of the year, with an absolute maximum of 130.94 µg/m³, nearly triple the maximum observed in Spring. - Variability: Winter exhibits the highest standard deviation (8.63), indicating that air quality during this period is the most volatile, likely due to intermittent stagnation and temperature inversion events. - Cleanest Season: Spring is established as the cleanest period of the year, characterized by the lowest average concentration (7.75 µg/m³) and the lowest variability (std of 4.72).</p>
</section>
<section id="spatial-patterns-top-metropolitan-areas" class="level3">
<h3 class="anchored" data-anchor-id="spatial-patterns-top-metropolitan-areas">Spatial Patterns: Top Metropolitan Areas</h3>
<div id="cell-fig-top-cbsa" class="cell" data-message="false" data-execution_count="16">
<div class="cell-output cell-output-display">
<div id="fig-top-cbsa" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-top-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-top-cbsa-output-1.png" width="756" height="566" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-top-cbsa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Figure 2: Top 15 Metropolitan Areas by Average Daily PM2.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>This bar plot highlights significant geographic disparities in air quality across major U.S. metropolitan areas in 2024. - Highest Burden: Phoenix-Mesa-Chandler, AZ ranks as the most polluted area in this sample, with an average daily PM2.5 concentration exceeding 16 µg/m³, followed closely by San Antonio-New Braunfels, TX. - Regional Clusters: Several Texas metropolitan areas (San Antonio and Houston) and Southwestern regions (Phoenix) dominate the top of the list, suggesting regional environmental factors such as high temperatures and specific industrial or transit-related emission profiles. - Comparison to National Average: All fifteen areas shown exceed the overall dataset mean of 9.76 µg/m³. Even the lowest-ranking city in this top group, Louisville/Jefferson County, KY-IN, maintains an average of approximately 11 µg/m³, indicating a sustained pollution burden compared to the rest of the country. - Consistency with Results: The high ranking of these predominantly warm-climate cities aligns with the previous findings that linked elevated PM2.5 levels to higher maximum temperatures (TMAX).</p>
<div id="cell-fig-spatial-map" class="cell" data-message="false" data-execution_count="17">
<div class="cell-output cell-output-display">
<div id="fig-spatial-map" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-spatial-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-spatial-map-output-1.png" width="1059" height="663" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-spatial-map-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Figure 3: Spatial Distribution of Annual Average PM2.5 across U.S. Monitoring Sites
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatter plot shoes a detailed Spatial Analysis (Verification with Data)</p>
<ul>
<li><p>Extreme Regional Hotspots: The data confirms that Phoenix-Mesa-Chandler, AZ (16.33 µg/m³) and San Antonio-New Braunfels, TX (13.56 µg/m³) are the primary drivers of the high-pollution cluster. Their values significantly exceed the national sample average of 9.76 µg/m³, which correlates with the previously observed trend where higher TMAX (Maximum Temperature) environments coincide with peak PM2.5.</p></li>
<li><p>Geographic Consistency: The inclusion of multiple Texas cities (San Antonio and Houston) and Southwestern hubs (Phoenix) in the top tier indicates that these high concentrations are not isolated incidents but represent regional atmospheric patterns. These areas often face a combination of high solar radiation (promoting secondary aerosol formation) and specific industrial/transportation densities.</p></li>
<li><p>Validation of Statistical Skewness: The fact that the top 15 cities all have means ranging from 11.23 µg/m³ to 16.33 µg/m³—all well above the median—further validates that the “right-skew” mentioned in the summary statistics is largely driven by these specific high-burden metropolitan corridors.</p></li>
</ul>
</section>
<section id="weather-and-pm2.5-relationships" class="level3">
<h3 class="anchored" data-anchor-id="weather-and-pm2.5-relationships">Weather and PM2.5 Relationships</h3>
<div id="cell-fig-tmax" class="cell" data-message="false" data-execution_count="18">
<div class="cell-output cell-output-display">
<div id="fig-tmax" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-tmax-output-1.png" width="668" height="449" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tmax-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Relationship between Daily Maximum Temperature and PM2.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatterplot reveals a significant non-linear relationship between maximum daily temperature (TMAX) and PM2.5 concentrations. While the majority of observations cluster at lower concentrations across all temperatures, the most severe pollution spikes (above 60 µg/m³) occur exclusively within the 15°C to 40°C range. This suggests that moderate-to-high temperatures are a key environmental prerequisite for extreme PM2.5 events in this dataset. These spikes are likely driven by enhanced secondary aerosol formation through photochemical reactions or seasonal events like summer wildfires, whereas extreme cold or extreme heat (&gt;45°C) appears to limit the potential for such high-concentration peaks.</p>
<div id="cell-fig-tmin" class="cell" data-message="false" data-execution_count="19">
<div class="cell-output cell-output-display">
<div id="fig-tmin" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-tmin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-tmin-output-1.png" width="667" height="449" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-tmin-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Relationship between Daily Minimum Temperature and PM2.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>The relationship between daily minimum temperature (TMIN) and PM2.5 concentrations reveals significant seasonal clustering. Most extreme pollution spikes (exceeding 60 µg/m³) are observed when the daily minimum temperature falls between 10°C and 25°C, which aligns with the previously identified high-pollution periods in summer and early autumn. Interestingly, while the data shows a broad distribution, very low minimum temperatures (below 0°C) exhibit relatively fewer extreme outliers compared to the moderate temperature range. This suggests that in the sampled metropolitan areas, the most hazardous air quality events are more closely tied to warm-season stagnant air masses or specific regional events (like wildfire smoke) rather than cold-weather temperature inversions alone.</p>
<div id="cell-fig-wind" class="cell" data-message="false" data-execution_count="20">
<div class="cell-output cell-output-display">
<div id="fig-wind" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wind-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-wind-output-1.png" width="667" height="449" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wind-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Relationship between Wind Direction and PM2.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>The relationship between wind direction (measured in degrees from 0° to 360°) and PM2.5 concentrations shows a fairly uniform distribution of observations across all compass headings. However, the most extreme PM2.5 spikes appear slightly more concentrated within specific directional corridors (e.g., around 150°–250°, or South/Southwest). While wind direction does not have a simple linear correlation with pollution levels, this clustering suggests that certain wind patterns may transport pollutants from major upwind emission sources—such as industrial zones or heavy traffic corridors—toward the monitoring stations. This finding highlights the importance of local geography and the directional positioning of pollution sources in urban air quality modeling.</p>
<div id="cell-fig-humidity" class="cell" data-message="false" data-execution_count="21">
<div class="cell-output cell-output-display">
<div id="fig-humidity" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-humidity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-humidity-output-1.png" width="667" height="449" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-humidity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Relationship between Relative Humidity and PM2.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatterplot confirms a significant, non-linear relationship between relative humidity (RH) and PM2.5 concentrations. There should be some physical properties we can relate to under this condition:</p>
<ul>
<li><p>Hygroscopic Growth Effect: A dense cluster of high PM2.5 observations is evident in the 40% to 80% RH range. This is a direct physical consequence of hygroscopic growth, where existing fine particulate matter absorbs atmospheric water vapor, increasing its mass and size, and thus raising the recorded concentration.</p></li>
<li><p>The Upper Threshold: Interestingly, as humidity approaches saturation (90%–100%), the concentration of PM2.5 tends to decrease. This is likely due to the fact that near-100% humidity is often associated with fog formation or precipitation events (the washout effect), which removes particles from the air.</p></li>
<li><p>Limiting Factors: The scarcity of extreme PM2.5 spikes at very low humidity (&lt;20%) suggests that moisture is often a necessary “facilitator” for reaching high aerosol mass concentrations in many urban environments.</p></li>
</ul>
<div id="cell-fig-prcp" class="cell" data-message="false" data-execution_count="22">
<div class="cell-output cell-output-display">
<div id="fig-prcp" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-prcp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-prcp-output-1.png" width="667" height="449" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-prcp-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: The Washout Effect: Precipitation vs PM2.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>The relationship between daily precipitation (PRCP) and PM2.5 concentrations exhibits a textbook example of the “washout effect” (or wet scavenging). The scatterplot follows a sharp L-shaped distribution, we will analysis it through the dry wet conditions:</p>
<ul>
<li><p>Dry Conditions: When precipitation is near zero, PM2.5 concentrations vary widely, capturing everything from clean-air days to extreme pollution spikes exceeding 120 µg/m³.</p></li>
<li><p>Wet Conditions: As soon as precipitation becomes significant (even &gt;10 mm), PM2.5 levels are immediately suppressed and remain consistently below 40 µg/m³.</p></li>
</ul>
<p>This confirms that rainfall acts as a primary natural cleanser of the atmosphere, physically removing fine particulate matter through wet deposition. The lack of high-pollution outliers during rainy periods highlights that dry, stagnant weather is a mandatory prerequisite for hazardous PM2.5 accumulation in these urban areas. Also the rainfall have the direct connection with the relative humidity above.</p>
<div id="cell-fig-pressure" class="cell" data-message="false" data-execution_count="23">
<div class="cell-output cell-output-display">
<div id="fig-pressure" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pressure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="JSC370_midterm_PM25_NOAA_AQS2.0_files/figure-html/fig-pressure-output-1.png" width="671" height="449" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pressure-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Relationship between Barometric Pressure and PM2.5
</figcaption>
</figure>
</div>
</div>
</div>
<p>The scatterplot reveals that PM2.5 concentrations are highly sensitive to variations in barometric pressure.</p>
<ul>
<li><p>High-Pressure Clustering: The most extreme PM2.5 spikes (exceeding 80 µg/m³) occur predominantly within the 1010 mb to 1030 mb range. In meteorology, high-pressure systems are often associated with sinking air and “stagnant” conditions. This creates a stable atmospheric boundary layer that acts as a lid, trapping urban pollutants near the surface and preventing them from dispersing.</p></li>
<li><p>Low-Pressure Clearance: Conversely, lower barometric pressure levels (often linked to stormy weather, wind, and instability) generally correspond to lower PM2.5 levels, as these conditions promote atmospheric mixing and pollutant removal.</p></li>
<li><p>Geographic Insights: The smaller cluster of data points located near 820–900 mb represents monitoring sites at higher altitudes (e.g., Denver or other mountain-region cities). The fact that PM2.5 levels remain relatively low in these low-pressure (high-altitude) environments further underscores that severe pollution is primarily a phenomenon of stable, high-pressure air masses at lower elevations.</p></li>
</ul>
</section>
</section>
<section id="summary-15-points" class="level2">
<h2 class="anchored" data-anchor-id="summary-15-points">Summary (15 points)</h2>
<section id="answer-to-the-proposed-research-questions" class="level3">
<h3 class="anchored" data-anchor-id="answer-to-the-proposed-research-questions">Answer to the proposed research questions</h3>
<p>Through the exploratory analysis of the 2024 CBSA-day level dataset, we provide the following answers to our initial research questions:</p>
<ul>
<li><p>Q1 for the Metropolitan Hotspots: The analysis identifies Phoenix-Mesa-Chandler, AZ, and several Texas metropolitan areas (e.g., San Antonio and Houston) as having the highest average daily PM2.5 levels in 2024. These areas consistently exceed the national average, often surpassing 13 µg/m³.</p></li>
<li><p>Q2 for the Temporal Patterns: PM2.5 levels exhibit a distinct bimodal seasonal trend. Peak concentrations occur in July/August (Summer) and January (Winter), while Spring (April-May) is identified as the cleanest period of the year with the lowest variability.</p></li>
<li><p>Q3 for the Weather Associations: Higher-PM2.5 days are strongly associated with specific meteorological “windows”: stagnant high-pressure systems (1010–1030 mb), dry conditions (the absence of the washout effect), and moderate-to-high temperatures (15°C–40°C). The data confirms that weather acts as a critical gatekeeper for pollution accumulation.</p></li>
</ul>
<p>The EDA reveals that PM2.5 concentrations are governed by non-random temporal, spatial, and meteorological patterns. Most notably, the relationship between weather variables (like humidity and precipitation) and air quality is predominantly non-linear. This complexity provides a strong empirical justification for utilizing advanced machine learning algorithms rather than simple linear regressions for the final forecasting phase.</p>
</section>
<section id="final-project-objectives" class="level3">
<h3 class="anchored" data-anchor-id="final-project-objectives">Final Project Objectives</h3>
<p>The final project will transition from descriptive analysis to predictive modeling, focusing on a two-pronged Machine Learning strategy:</p>
<ul>
<li><p>Regression Modeling: To predict the precise daily arithmetic_mean of PM2.5. This will be used to understand the exact sensitivity of air quality to incremental changes in weather parameters.</p></li>
<li><p>Classification Modeling: To categorize air quality into discrete risk levels (e.g., based on AQI thresholds: Good, Moderate, Unhealthy). This approach is more aligned with public health decision-making, where the goal is to trigger alerts rather than predicting exact concentrations.</p></li>
</ul>
</section>
<section id="implementation-plan" class="level3">
<h3 class="anchored" data-anchor-id="implementation-plan">Implementation Plan</h3>
<p>To achieve these objectives, the following steps will be executed:</p>
<p>Step 1: Feature Engineering &amp; Pre-processing: Handle the cyclical nature of wind direction using trigonometric transformations (sine/cosine). Also integrate temporal features (month, day of week) and regional indicators to capture localized trends.</p>
<p>Step 2: Model Development &amp; Selection: We will evaluate non-linear models such as Random Forest, XGBoost, or Support Vector Machines (SVM) to handle the complex interactions identified in the scatterplots. For Classification, we will implement multi-class classifiers to predict AQI categories.</p>
<p>Step 3: Interactive Visualizations: Develop an interactive dashboard (using Plotly or Leaflet) that allows users to explore PM2.5 levels across the U.S. in real-time.</p>
<p>Step 4: Web Development: The entire analysis and the trained models will be hosted on a dedicated website (via Quarto Pub or GitHub Pages), providing an accessible platform for stakeholders to interact with our predictive tools.</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>