<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Yukun Wang">
<meta name="dcterms.date" content="2026-04-26">

<title>Daily PM2.5 and Weather Conditions Across Major U.S. Metropolitan Areas in 2024 – PM2.5 Prediction</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e31584831b205ffbb2d98406f31c2a5b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">PM2.5 Prediction</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./visualizations.html"> 
<span class="menu-text">Interactive Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./report.html" aria-current="page"> 
<span class="menu-text">Report</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/NKwyk/JSC370-project"> <i class="bi bi-github" role="img" aria-label="GitHub repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://jsc370.github.io/JSC370-2026/"> 
<span class="menu-text">JSC370</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#methods" id="toc-methods" class="nav-link" data-scroll-target="#methods"><span class="header-section-number">2</span> Methods</a>
  <ul class="collapse">
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">2.1</span> Data</a></li>
  <li><a href="#feature-engineering" id="toc-feature-engineering" class="nav-link" data-scroll-target="#feature-engineering"><span class="header-section-number">2.2</span> Feature Engineering</a></li>
  <li><a href="#modeling-strategy" id="toc-modeling-strategy" class="nav-link" data-scroll-target="#modeling-strategy"><span class="header-section-number">2.3</span> Modeling Strategy</a></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">3</span> Results</a>
  <ul class="collapse">
  <li><a href="#descriptive-patterns" id="toc-descriptive-patterns" class="nav-link" data-scroll-target="#descriptive-patterns"><span class="header-section-number">3.1</span> Descriptive Patterns</a></li>
  <li><a href="#regression-models" id="toc-regression-models" class="nav-link" data-scroll-target="#regression-models"><span class="header-section-number">3.2</span> Regression Models</a></li>
  <li><a href="#high-pm2.5-classification" id="toc-high-pm2.5-classification" class="nav-link" data-scroll-target="#high-pm2.5-classification"><span class="header-section-number">3.3</span> High PM2.5 Classification</a></li>
  </ul></li>
  <li><a href="#conclusions-and-limitations" id="toc-conclusions-and-limitations" class="nav-link" data-scroll-target="#conclusions-and-limitations"><span class="header-section-number">4</span> Conclusions and Limitations</a>
  <ul class="collapse">
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">4.1</span> Conclusions</a></li>
  <li><a href="#limitations" id="toc-limitations" class="nav-link" data-scroll-target="#limitations"><span class="header-section-number">4.2</span> Limitations</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="report.pdf"><i class="bi bi-file-pdf"></i>Typst</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Daily PM2.5 and Weather Conditions Across Major U.S. Metropolitan Areas in 2024</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Yukun Wang </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">April 26, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>PM2.5 refers to fine particulate matter with diameter less than or equal to 2.5 micrometers. These particles are small enough to enter the respiratory system, so elevated PM2.5 is a public health concern. In my midterm project, I described 2024 PM2.5 patterns across major U.S. metropolitan areas and examined how pollution changed by place, season, and weather conditions.</p>
<p>This final project extends that work from exploratory analysis to prediction. The main research question is:</p>
<blockquote class="blockquote">
<p>How are daily PM2.5 levels associated with temperature, precipitation, wind, pressure, and humidity across major U.S. metropolitan areas in 2024, and can these weather and location features help predict high-pollution days?</p>
</blockquote>
<p>I study two related modeling tasks. First, I predict daily mean PM2.5 as a continuous outcome. Second, I classify whether a monitor-day exceeds 35 ug/m3, a high-pollution threshold used in the midterm feedback and final project plan.</p>
</section>
<section id="methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Methods</h1>
<section id="data" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="data"><span class="header-section-number">2.1</span> Data</h2>
<p>The dataset used in this project was generated by combining air pollution data from the EPA Air Quality System (AQS) with weather data from both EPA AQS and the NOAA Climate Data Online (CDO) API. The EPA AQS data provided daily PM2.5 monitor-level observations, as well as daily wind speed, barometric pressure, and relative humidity/dew point variables. The NOAA CDO API was used to retrieve daily maximum temperature, minimum temperature, and precipitation for selected weather stations representing major U.S. metropolitan areas. These data sources were combined so that each PM2.5 monitor-day observation could be linked with local weather, geographic, and temporal information.</p>
<p>After the raw EPA and NOAA data were merged, the project analysis began from the cleaned CSV file <code>pm25_weather_local_2024_2.0.csv</code>. In this step, the date variable was parsed into datetime format, and several additional variables were created for analysis. A binary <code>high_pm25_day</code> variable was defined to indicate whether the daily PM2.5 arithmetic mean exceeded 35 µg/m³. I also created time-based variables, including <code>day_of_year</code>, abbreviated month names, and cyclic month features using sine and cosine transformations to better represent seasonal patterns. Each monitor was identified using <code>state_code</code>, <code>county_code</code>, <code>site_num</code>, and <code>poc</code>, where POC distinguishes monitor occurrences at the same site. POC was retained only as part of the monitor identifier and was not used as an analytical predictor.</p>
<p><strong>Table 1. Dataset summary.</strong></p>
<div id="072a7610" class="cell" data-execution_count="3">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Quantity</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Monitor-day observations</td>
<td style="text-align: left;">13,057</td>
</tr>
<tr class="even">
<td style="text-align: left;">Unique PM2.5 monitors</td>
<td style="text-align: left;">83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Metropolitan areas</td>
<td style="text-align: left;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Date range</td>
<td style="text-align: left;">2024-01-01 to 2024-12-31</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mean daily PM2.5</td>
<td style="text-align: left;">8.84 ug/m3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Median daily PM2.5</td>
<td style="text-align: left;">7.72 ug/m3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Maximum daily PM2.5</td>
<td style="text-align: left;">130.94 ug/m3</td>
</tr>
<tr class="even">
<td style="text-align: left;">High PM2.5 days (&gt;35 ug/m3)</td>
<td style="text-align: left;">74 (0.57%)</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="feature-engineering" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="feature-engineering"><span class="header-section-number">2.2</span> Feature Engineering</h2>
<p>The outcome for regression is <code>arithmetic_mean</code>, the daily mean PM2.5 concentration. The classification outcome is <code>high_pm25_day</code>, equal to 1 when daily PM2.5 is greater than 35 µg/m³. I use this threshold because 35 µg/m³ corresponds to the U.S. EPA 24-hour PM2.5 standard, making it a policy-relevant cutoff for identifying unusually high daily PM2.5 monitor-days. This threshold is used for classification rather than for formal regulatory attainment determinations.</p>
<p>Predictors include:</p>
<ul>
<li>Weather: maximum temperature, minimum temperature, precipitation, wind, pressure, relative humidity, and dew point.</li>
<li>Space: latitude, longitude, state, and CBSA.</li>
<li>Time: month, season, day of year, and cyclic month sine/cosine terms.</li>
</ul>
<p>To avoid target leakage, PM2.5-derived fields such as <code>pm25_max</code>, <code>aqi</code>, and <code>high_pm25_day</code> are excluded from the regression predictors, and PM2.5 concentration variables are excluded from classification predictors.</p>
</section>
<section id="modeling-strategy" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="modeling-strategy"><span class="header-section-number">2.3</span> Modeling Strategy</h2>
<p>I compare Random Forest and XGBoost models because they are well suited for nonlinear relationships and interactions among weather, location, and season. Both methods were covered in the course labs. Random Forest averages many decision trees to reduce variance. XGBoost builds boosted trees sequentially and uses regularization to control overfitting.</p>
<p>For regression, I use a 70/30 train-test split and report RMSE, MAE, and R-squared. Random Forest and XGBoost hyperparameters are selected using 3-fold cross-validation on the training set, with negative RMSE as the tuning criterion. For the regression Random Forest, the grid searches <code>max_features</code> values of 0.3, 0.6, and <code>"sqrt"</code>, and <code>min_samples_leaf</code> values of 1 and 5. For the regression XGBoost model, the grid searches <code>max_depth</code> values of 2, 4, and 6, and <code>learning_rate</code> values of 0.01 and 0.08.</p>
<p>For classification, I use a stratified 70/30 train-test split because the high-pollution class is rare. Classification hyperparameters are selected using stratified 3-fold cross-validation with F1 as the tuning criterion. The Random Forest classifier uses class-balanced sampling and searches the same <code>max_features</code> and <code>min_samples_leaf</code> values as the regression Random Forest. The XGBoost classifier uses <code>scale_pos_weight</code> and searches <code>max_depth</code> values of 2, 4, and 6, and <code>learning_rate</code> values of 0.01 and 0.08. After cross-validation selects the XGBoost classifier hyperparameters, I use a validation split from the training data to choose the probability threshold that maximizes F1.</p>
</section>
</section>
<section id="results" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Results</h1>
<section id="descriptive-patterns" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="descriptive-patterns"><span class="header-section-number">3.1</span> Descriptive Patterns</h2>
<p><strong>Table 2. CBSA summary, sorted by annual mean PM2.5.</strong></p>
<div id="0d27b61e" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 30%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 14%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">cbsa_name</th>
<th style="text-align: right;">monitor_days</th>
<th style="text-align: right;">monitors</th>
<th style="text-align: right;">mean_pm25</th>
<th style="text-align: right;">max_pm25</th>
<th style="text-align: right;">high_pm25_days</th>
<th style="text-align: right;">high_day_rate</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Riverside-San Bernardino-Ontario, CA</td>
<td style="text-align: right;">1682</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">12.33</td>
<td style="text-align: right;">130.94</td>
<td style="text-align: right;">36</td>
<td style="text-align: right;">2.14</td>
</tr>
<tr class="even">
<td style="text-align: left;">Los Angeles-Long Beach-Anaheim, CA</td>
<td style="text-align: right;">1551</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">11.46</td>
<td style="text-align: right;">68.2</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">1.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Cleveland-Elyria, OH</td>
<td style="text-align: right;">91</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">11.06</td>
<td style="text-align: right;">22.81</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">Houston-The Woodlands-Sugar Land, TX</td>
<td style="text-align: right;">1051</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">10.44</td>
<td style="text-align: right;">46.8</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.67</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dallas-Fort Worth-Arlington, TX</td>
<td style="text-align: right;">328</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">10.14</td>
<td style="text-align: right;">36.33</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.3</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 2 summarizes the metropolitan areas with the highest average daily PM2.5 concentrations in the final dataset. Riverside-San Bernardino-Ontario, CA has the highest mean PM2.5 level, with an average of 12.33 µg/m³ across 1,682 monitor-day observations, followed by Los Angeles-Long Beach-Anaheim, CA with an average of 11.46 µg/m³. These two Southern California metropolitan areas also have the largest numbers of high-PM2.5 monitor-days, suggesting that elevated PM2.5 events in this dataset are spatially concentrated in Southern California. Other metropolitan areas such as Cleveland, Houston, and Dallas also appear among the top five by mean PM2.5, but they show fewer or no high-pollution days above 35 µg/m³. Because the number of monitors and monitor-days differs across metropolitan areas, these results should be interpreted as descriptive comparisons rather than population-weighted exposure estimates.</p>
<div id="cell-fig-monthly-static" class="cell" data-execution_count="8">
<div class="cell-output cell-output-display">
<div id="fig-monthly-static" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-monthly-static-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-monthly-static-output-1.png" width="854" height="437" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monthly-static-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Figure 1. Monthly distribution of daily PM2.5 monitor-day concentrations in 2024.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The Figure shows the monthly distribution of daily PM2.5 concentrations across monitor-day observations. Median PM2.5 levels remain relatively low in most months, but the spread and number of high outliers vary substantially across the year. July shows the most extreme PM2.5 values, including the highest observed concentration in the dataset, while December also has many observations above the 35 µg/m³ threshold. These patterns suggest that high-PM2.5 events are episodic rather than evenly distributed across all months. The July peak is consistent with the wildfire-smoke interpretation discussed in the midterm report, although wildfire exposure is treated as contextual evidence rather than a directly modeled variable in this final analysis.</p>
</section>
<section id="regression-models" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="regression-models"><span class="header-section-number">3.2</span> Regression Models</h2>
<p><strong>Table 3. Cross-validation selected hyperparameters for regression models.</strong></p>
<div id="0b7203d0" class="cell" data-execution_count="9">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 21%">
<col style="width: 23%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Best CV RMSE</th>
<th style="text-align: left;">Best parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: right;">3.55</td>
<td style="text-align: left;">max_features=0.6, min_samples_leaf=1</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">3.437</td>
<td style="text-align: left;">learning_rate=0.08, max_depth=6</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 3 shows the hyperparameters selected by cross-validation for the two regression models. The Random Forest model achieved a lower cross-validation RMSE than XGBoost, suggesting that the bagged-tree approach fit this dataset more effectively during tuning. The selected Random Forest model used half of the available features at each split and allowed small terminal nodes, which gives the model flexibility to capture local variation across time, weather, and metropolitan areas. The selected XGBoost model used a moderate tree depth and learning rate, but its higher CV RMSE suggests weaker predictive performance for this regression task.</p>
<p><strong>Table 4. Regression model performance on the test set.</strong></p>
<div id="aed17362" class="cell" data-execution_count="10">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">RMSE</th>
<th style="text-align: right;">MAE</th>
<th style="text-align: right;">R-squared</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: right;">3.295</td>
<td style="text-align: right;">2.061</td>
<td style="text-align: right;">0.661</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">3.306</td>
<td style="text-align: right;">2.068</td>
<td style="text-align: right;">0.658</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 4 compares model performance on the held-out test set. Random Forest performs better than XGBoost across all three regression metrics, with a lower RMSE, lower MAE, and higher R-squared. The Random Forest test RMSE of 3.318 µg/m³ means that its daily PM2.5 predictions are typically off by about 3.3 µg/m³. Its R-squared of 0.656 indicates that the model explains about 65.6% of the variation in daily mean PM2.5 in the test data. Therefore, Random Forest is selected as the best regression model for interpreting feature importance.</p>
<div id="cell-fig-reg-importance" class="cell" data-execution_count="11">
<div class="cell-output cell-output-display">
<div id="fig-reg-importance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-reg-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-reg-importance-output-1.png" width="757" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-reg-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Figure 2. Aggregated feature importance for the best regression model.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 2 presents the aggregated feature importance from the best regression model, the Random Forest regressor. The most important predictor is day_of_year, showing that temporal variation is central to explaining daily PM2.5 patterns. Spatial variables such as latitude and longitude also rank highly, which suggests that PM2.5 levels vary substantially across geographic regions. Weather variables including maximum temperature, pressure, wind speed, relative humidity, minimum temperature, and dew point also contribute meaningfully to prediction. Overall, the feature importance results support the midterm finding that PM2.5-weather relationships are nonlinear and geographically uneven, rather than driven by a single weather variable.</p>
</section>
<section id="high-pm2.5-classification" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="high-pm2.5-classification"><span class="header-section-number">3.3</span> High PM2.5 Classification</h2>
<p>High-PM2.5 days above 35 ug/m3 are rare in the dataset, so accuracy alone is not a useful measure. A model could achieve high accuracy by predicting almost every day as non-high. For that reason, I focus on balanced accuracy, recall, precision, F1, ROC-AUC, and PR-AUC.</p>
<p><strong>Table 5. Cross-validation selected hyperparameters for classification models.</strong></p>
<div id="2dbce6cb" class="cell" data-execution_count="12">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Best CV F1</th>
<th style="text-align: left;">Best parameters</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: right;">0.483</td>
<td style="text-align: left;">max_features=0.6, min_samples_leaf=5</td>
</tr>
<tr class="even">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">0.458</td>
<td style="text-align: left;">learning_rate=0.08, max_depth=4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 5 shows the cross-validation results for the high-PM2.5 classification models. Random Forest achieves a higher cross-validation F1 score than XGBoost, suggesting that it performed better during tuning when precision and recall were balanced together. However, because high-PM2.5 days are rare, the final test-set comparison is more important for evaluating whether the model can actually identify high-pollution events.</p>
<p><strong>Table 6. Classification model performance for PM2.5 greater than 35 ug/m3.</strong></p>
<div id="6241028e" class="cell" data-execution_count="13">
<div class="cell-output cell-output-display cell-output-markdown">
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 17%">
<col style="width: 8%">
<col style="width: 15%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 5%">
<col style="width: 8%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Model</th>
<th style="text-align: right;">Threshold</th>
<th style="text-align: right;">Predicted positives</th>
<th style="text-align: right;">Accuracy</th>
<th style="text-align: right;">Balanced accuracy</th>
<th style="text-align: right;">Precision</th>
<th style="text-align: right;">Recall</th>
<th style="text-align: right;">F1</th>
<th style="text-align: right;">ROC-AUC</th>
<th style="text-align: right;">PR-AUC</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">XGBoost</td>
<td style="text-align: right;">0.501</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">0.996</td>
<td style="text-align: right;">0.749</td>
<td style="text-align: right;">0.647</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">0.564</td>
<td style="text-align: right;">0.965</td>
<td style="text-align: right;">0.541</td>
</tr>
<tr class="even">
<td style="text-align: left;">Random Forest</td>
<td style="text-align: right;">0.5</td>
<td style="text-align: right;">21</td>
<td style="text-align: right;">0.995</td>
<td style="text-align: right;">0.772</td>
<td style="text-align: right;">0.571</td>
<td style="text-align: right;">0.545</td>
<td style="text-align: right;">0.558</td>
<td style="text-align: right;">0.991</td>
<td style="text-align: right;">0.561</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 6 compares the two classifiers on the held-out test set. Both models have very high accuracy, but this is mainly because most days are not high-PM2.5 days. The more useful metrics are balanced accuracy, recall, F1, ROC-AUC, and PR-AUC. XGBoost predicts more positive cases and achieves higher recall and F1, meaning it identifies more high-PM2.5 events than Random Forest. Random Forest has higher precision, ROC-AUC, and PR-AUC, but it only predicts 7 positive cases and misses more true high-pollution events. Since the goal of this classification task is closer to warning detection, XGBoost is selected as the better practical classifier.</p>
<div id="cell-fig-confusion" class="cell" data-execution_count="14">
<div class="cell-output cell-output-display">
<div id="fig-confusion" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-confusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-confusion-output-1.png" width="452" height="422" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-confusion-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Figure 3. Confusion matrix for the best high-PM2.5 classifier on the test set.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The confusion matrix shows the tradeoff in the selected XGBoost classifier. The model correctly identifies 12 high-PM2.5 observations, while missing 10 high-PM2.5 observations. It also produces 9 false positives among the non-high observations. This result is reasonable for a rare-event warning task: the model does not capture every high-pollution episode, but it detects more events than the Random Forest classifier while keeping the number of false alarms relatively small.</p>
<div id="cell-fig-clf-importance" class="cell" data-execution_count="15">
<div class="cell-output cell-output-display">
<div id="fig-clf-importance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-clf-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="report_files/figure-html/fig-clf-importance-output-1.png" width="758" height="470" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-clf-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Figure 4. Aggregated feature importance for the best high-PM2.5 classifier.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure 4 shows that the most important predictors for high-PM2.5 classification are spatial and seasonal variables. cbsa_name, season, state_name, and longitude have the largest importance values, suggesting that high-pollution events are strongly shaped by where and when they occur. Weather variables such as precipitation, temperature, and wind also contribute, but they are less dominant than location and season. This supports the interpretation that high PM2.5 episodes are not explained by a single weather factor alone; instead, they reflect interactions between geography, seasonality, and meteorological conditions.</p>
<p>Overall, the classification results should be interpreted as a high-pollution warning task rather than a balanced everyday classification problem. XGBoost is useful here because class weighting and probability threshold adjustment improve recall for rare high-PM2.5 events. The tradeoff is that the model may produce some false positives, which is expected when the goal is to identify rare hazardous episodes rather than simply maximize overall accuracy.</p>
<p>The full interactive versions of the spatial and weather figures are available on the <a href="visualizations.html">interactive visualizations page</a>.</p>
</section>
</section>
<section id="conclusions-and-limitations" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Conclusions and Limitations</h1>
<section id="conclusions" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="conclusions"><span class="header-section-number">4.1</span> Conclusions</h2>
<p>This project shows that daily PM2.5 variation is shaped by a combination of location, season, and weather conditions. The descriptive results show clear spatial differences across metropolitan areas, with some regions having higher average PM2.5 and more high-pollution monitor-days than others. The monthly distribution also suggests that extreme PM2.5 events are not evenly distributed throughout the year, but instead appear more strongly in specific periods such as July and winter months.</p>
<p>The modeling results support the idea that PM2.5 prediction requires both environmental and contextual information. Weather variables such as temperature, precipitation, wind, humidity, and pressure contribute to prediction, but location and time variables are also important. This suggests that PM2.5 is not driven by one single weather factor. Instead, pollution levels reflect interactions between geography, seasonality, and meteorological conditions.</p>
<p>For continuous PM2.5 prediction, the Random Forest model performs better than XGBoost on the test set, with lower prediction error and higher R-squared. For high-PM2.5 classification, XGBoost is more useful as a warning-oriented model because it identifies more rare high-pollution events. Overall, the project shows that tree-based machine learning models can provide useful predictive summaries of PM2.5 patterns, but the results should be interpreted as predictive associations rather than causal explanations.</p>
</section>
<section id="limitations" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="limitations"><span class="header-section-number">4.2</span> Limitations</h2>
<ul>
<li><p>First, the train-test split is based on a random split of monitor-day observations. This is useful for measuring general predictive performance, but it is not the strictest test of generalization. Since observations from the same monitor, city, or season can appear in both the training and testing sets, the model may partially benefit from repeated spatial or temporal patterns. A more rigorous future approach would use grouped splitting by monitor or city, or time-based splitting where earlier months are used for training and later months are used for testing.</p></li>
<li><p>Second, the high-PM2.5 classification task is highly imbalanced. The threshold of 35 µg/m³ is relatively high, so most observations are classified as non-high days. Because of this, accuracy can look very high even when the model does not identify many true high-pollution events. This is why balanced accuracy, recall, F1, ROC-AUC, and PR-AUC are more informative than accuracy alone.</p></li>
<li><p>Third, the 35 µg/m³ threshold is useful for defining extreme PM2.5 days, but it may be too strict for some metropolitan areas where daily PM2.5 rarely reaches that level. As a result, the classification model is mainly detecting rare pollution spikes rather than more moderate but still meaningful pollution variation. Future work could test alternative thresholds or use multi-class air-quality categories.</p></li>
<li><p>Fourth, wildfire smoke is discussed as a possible explanation for some summer PM2.5 peaks, especially the July outliers, but wildfire exposure is not directly measured in the model. More broadly, the model does not directly include episodic external events such as wildfire smoke, dust storms, extreme heat events, regional pollution transport, or other natural-disaster-related air quality shocks. Therefore, these factors should be treated as contextual interpretations rather than causal variables. Future work could add smoke plume data, fire counts, satellite aerosol measurements, dust event indicators, extreme-weather indicators, or distance-to-fire variables to better capture these short-term pollution episodes.</p></li>
<li><p>Fifth, NOAA temperature and precipitation variables are attached at the broader metropolitan level, while PM2.5 is measured at individual monitoring sites. This mismatch may miss local microclimate differences near specific monitors. More localized weather station matching or spatial interpolation could improve the precision of the weather variables.</p></li>
<li><p>Finally, the analysis only uses data from 2024. One year of data is enough for a course project, but it may not fully represent longer-term PM2.5 patterns. Future work could extend the dataset across multiple years to test whether the same spatial, seasonal, and weather relationships remain stable over time.</p></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<footer></footer>

<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/NKwyk\.github\.io\/JSC370-project\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>Copyright © 2026 Yukun Wang. Built for JSC370.</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>